### ISSUE TITLE
docker-compose -f single-peer-ca.yaml up Failed requesting read certificate

### ISSUE THREAD

**Issue by YvesHarrison** [IBM-Blockchain-Archive/fabric-images#33]
The program was fine in August. It suddenly crash down facing problem below:
E:\p\src\github.com\hyperledger\fabric-images\docker-compose>docker-compose -f single-peer-ca.yaml up
Recreating dockercompose_baseimage_1 ...
Starting dockercompose_membersrvc_1 ...
Recreating dockercompose_baseimage_1
Starting dockercompose_membersrvc_1 ... done
Starting dockercompose_vp_1 ...
Starting dockercompose_vp_1 ... done
Attaching to dockercompose_membersrvc_1, dockercompose_baseimage_1, dockercompose_vp_1
dockercompose_baseimage_1 exited with code 0
membersrvc_1  | 07:53:48.978 [server] main -> INFO 001 CA Server (0.6.1-preview)
membersrvc_1  | 07:53:49.076 [eca] Stop -> INFO 002 Stopping ECA services...
membersrvc_1  | 07:53:49.076 [eca] Stop -> INFO 003 ECA stopped
membersrvc_1  | 07:53:49.076 [aca] Stop -> INFO 004 Stopping the ACA services...
membersrvc_1  | 07:53:49.076 [aca] Stop -> INFO 005 ACA services stopped
membersrvc_1  | panic: runtime error: invalid memory address or nil pointer dereference
membersrvc_1  | [signal 0xb code=0x1 addr=0x0 pc=0x4dea5a]
membersrvc_1  |
membersrvc_1  | goroutine 1 [running]:
membersrvc_1  | panic(0xb22a40, 0xc82000a0a0)
membersrvc_1  |         /opt/go/src/runtime/panic.go:464 +0x3e6
membersrvc_1  | github.com/hyperledger/fabric/membersrvc/ca.(*CA).readCAPrivateKey(0xc82026a880, 0xbff648, 0x3, 0x2e, 0x0, 0x0)
membersrvc_1  |         /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ca/ca.go:335 +0x27a
membersrvc_1  | github.com/hyperledger/fabric/membersrvc/ca.NewCA(0xbff648, 0x3, 0xd3e150, 0x43d32d)
membersrvc_1  |         /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ca/ca.go:257 +0x78c
membersrvc_1  | github.com/hyperledger/fabric/membersrvc/ca.NewTCA(0xc8201b2fc0, 0xd3e128)
membersrvc_1  |         /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ca/tca.go:90 +0x3c
membersrvc_1  | main.main()
membersrvc_1  |         /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/server.go:79 +0x752
dockercompose_membersrvc_1 exited with code 2
vp_1          | 07:53:58.773 [logging] LoggingInit -> DEBU 001 Setting default logging level to DEBUG for command 'node'
vp_1          | 07:53:58.800 [peer] func1 -> INFO 002 Auto detected peer address: 172.18.0.4:7051
vp_1          | 07:53:58.814 [peer] func1 -> INFO 003 Auto detected peer address: 172.18.0.4:7051
vp_1          | 07:53:58.816 [eventhub_producer] AddEventType -> DEBU 004 registering BLOCK
vp_1          | 07:53:58.816 [eventhub_producer] AddEventType -> DEBU 005 registering CHAINCODE
vp_1          | 07:53:58.816 [eventhub_producer] AddEventType -> DEBU 006 registering REJECTION
vp_1          | 07:53:58.816 [eventhub_producer] AddEventType -> DEBU 007 registering REGISTER
vp_1          | 07:53:58.817 [nodeCmd] serve -> INFO 008 Security enabled status: true
vp_1          | 07:53:58.817 [nodeCmd] serve -> INFO 00a Privacy enabled status: false
vp_1          | 07:53:58.817 [eventhub_producer] start -> INFO 009 event processor started
vp_1          | 07:53:58.824 [db] open -> DEBU 00b Is db path [/var/hyperledger/production/db] empty [false]
vp_1          | 07:53:58.828 [db] open -> INFO 00c Setting rocksdb maxLogFileSize to 10485760
vp_1          | 07:53:58.829 [db] open -> INFO 00d Setting rocksdb keepLogFileNum to 10
vp_1          | 07:53:59.370 [nodeCmd] func1 -> DEBU 00e Registering validator with enroll ID: vp
vp_1          | 07:53:59.370 [crypto] RegisterValidator -> INFO 00f Registering validator [vp] with name [vp]...
vp_1          | 07:53:59.393 [crypto] Debugf -> DEBU 010 [validator.vp] Data will be stored at [/var/hyperledger/production/crypto/validator/vp]
vp_1          | 07:53:59.408 [crypto] Debugf -> DEBU 011 [validator.vp] Keystore path [/var/hyperledger/production/crypto/validator/vp/ks] missing [false]: [<clean>]
vp_1          | 07:53:59.408 [crypto] Debugf -> DEBU 012 [validator.vp] Keystore [/var/hyperledger/production/crypto/validator/vp/ks/db] missing [false]:[<clean>]
vp_1          | 07:53:59.408 [crypto] Debugf -> DEBU 013 [validator.vp] Keystore opened at [/var/hyperledger/production/crypto/validator/vp/ks]...done
vp_1          | 07:53:59.408 [crypto] Debug -> DEBU 014 [validator.vp]  Registering node crypto engine...
vp_1          | 07:53:59.409 [crypto] Debug -> DEBU 015 [validator.vp]  Initiliazing TLS...
vp_1          | 07:53:59.409 [crypto] Debug -> DEBU 016 [validator.vp]  Initiliazing TLS...Disabled!!!
vp_1          | 07:53:59.410 [crypto] Debug -> DEBU 017 [validator.vp]  Getting ECA client...
vp_1          | 07:53:59.410 [crypto] Debugf -> DEBU 018 [validator.vp] Dial to addr:[membersrvc:7054], with serverName:[tlsca]...
vp_1          | 07:53:59.410 [crypto] Debug -> DEBU 019 [validator.vp]  TLS disabled...
vp_1          | 07:53:59.410 [crypto] Debug -> DEBU 01a [validator.vp]  Getting ECA client...done
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01b [validator.vp] Failed requesting read certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01c [validator.vp] Failed requesting ECA certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 2017/09/11 07:53:59 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup membersrvc on 127.0.0.11:53: no such host"; Reconnecting to {"membersrvc:7054" <nil>}
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01d [validator.vp] Failed getting ECA certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 2017/09/11 07:53:59 Failed to dial membersrvc:7054: grpc: the connection is closing; please retry.
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01e [validator.vp] Failed retrieving ECA certs chain [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01f [validator.vp] Failed registering node crypto engine [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 020 [validator.vp] Failed registering peer [vp]: [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure]
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 021 [validator.vp] Failed registering [vp]: [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure]
vp_1          | 07:53:59.464 [crypto] RegisterValidator -> ERRO 022 Failed registering validator [vp] with name [vp] [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | Error: rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure
vp_1          | Usage:
vp_1          |   peer node start [flags]
vp_1          |
vp_1          | Flags:
vp_1          |   -h, --help                help for start
vp_1          |       --peer-chaincodedev   Whether peer in chaincode development mode
vp_1          |
vp_1          | Global Flags:
vp_1          |       --logging-level string       Default logging level and overrides, see core.yaml for full syntax
vp_1          |       --test.coverprofile string   Done (default "coverage.cov")
vp_1          |   -v, --version                    Display current version of fabric peer server
vp_1          |
dockercompose_vp_1 exited with code 1

**Comment by YvesHarrison** [comment]
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01b [validator.vp] Failed requesting read certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01c [validator.vp] Failed requesting ECA certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 2017/09/11 07:53:59 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup membersrvc on 127.0.0.11:53: no such host"; Reconnecting to {"membersrvc:7054" <nil>}
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01d [validator.vp] Failed getting ECA certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 2017/09/11 07:53:59 Failed to dial membersrvc:7054: grpc: the connection is closing; please retry.
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01e [validator.vp] Failed retrieving ECA certs chain [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 01f [validator.vp] Failed registering node crypto engine [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 020 [validator.vp] Failed registering peer [vp]: [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure]
vp_1          | 07:53:59.463 [crypto] Errorf -> ERRO 021 [validator.vp] Failed registering [vp]: [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure]
vp_1          | 07:53:59.464 [crypto] RegisterValidator -> ERRO 022 Failed registering validator [vp] with name [vp] [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].
vp_1          | Error: rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure
